### ISSUE TITLE
Public Sharing

### ISSUE THREAD

**Issue by MrPigeontheCoder** [GrantGryczan/web#46]
Basically allow people to just sorta make their stuff public, and add a sidebar that allows for browsing public files and stuff

**Comment by GrantGryczan** [comment]
That option already exists. There's a privacy option for each file and for each directory, where you can set items to be public. You can browse public files if you have a link to a directory with public items in it (the same URL you use to access the directory yourself, on filegarden.com rather than file.garden).

There is no place to browse all users' public files without a link to a directory containing the files, because that would turn File Garden into a social media site that requires significantly more complexity and moderation.

**Comment by MrPigeontheCoder** [comment]
Oh, i didn't know. Thanks for explaining!
